### ISSUE TITLE
ProductReview resource needs an update

### ISSUE THREAD

**Issue by bc-jz** [bigcommerce/bigcommerce-api-ruby#106]
The ProductReview resource is currently written with only a GET request in mind.  This resource is now fully writable on the API and needs to be updated to act like other product subresources, such as Sku.

**Comment by aleachjr** [comment]
pull requests welcome :smile:

**Comment by pedelman** [comment]
Thanks @bc-jz this will be updated for the 1.0.0 release. Stay tuned.
