### ISSUE TITLE
About time for a release?

### ISSUE THREAD

**Issue by jcwilk** [bigcommerce/bigcommerce-api-ruby#108]
Hey guys,

Thanks for providing a ruby client, but it's been about 9 months since the last release and there's at least one fix our code depends on since the last release (1.0.0.beta in march '15) which means we have to specify the gem by SHA in all our Gemfiles and can't list the specific version as an internal gem dependency (SHAs work for Gemfiles, not gemspecs).

Since you recommend that developers upgrade to the beta version in the README and it's been out for awhile and presumably widely in use in production, seems like that roughly fits the criteria for bumping it to 1.0.0 and beyond?

All 1.0.0 means is that further changes will respect major, minor, patchlevel version adjustments dependent on changes to the public API, which would be a useful thing to depend on for us and I'm sure others would appreciate it as well.

Thanks,
John Wilkinson
ReferralCandy

**Comment by mattolson** [comment]
Agreed, I will discuss this with the team and cut a release soon.

**Comment by jcwilk** [comment]
Thanks! :palm_tree:

**Comment by pedelman** [comment]
Will be cutting a release very soon -- doing some house keeping and want to address open issues / pull requests.
