### ISSUE TITLE
Viewing price for SKU 

### ISSUE THREAD

**Issue by sollabeck** [bigcommerce/bigcommerce-api-ruby#110]
Does the gem support the price field for SKUs? I can't seem to see it in the response. Perhaps I'm missing something obvious. Apologies if that is the case.

**Problem:**
I see that [price is a property](https://developer.bigcommerce.com/api/objects/v2/sku) of SKU, however I set a price on the BigCommerce web dashboard, and cannot see it when I use the gem to query the SKU.

**Environment**

-  Ruby 1.9.3p551
- Rails 3.2.15
- Gem: bigcommerce 1.0.0.beta

**Steps to reproduce**
SKU on BigCommerce (saved changes): 
![](https://s3.amazonaws.com/f.cl.ly/items/1d0P3N3J340e2X1d1c1F/Image%202016-04-19%20at%202.45.04%20PM.png?v=0c78bc36)

Gem Query Response: 
![](https://s3.amazonaws.com/f.cl.ly/items/3m2D1V453K3C071V3r2S/Image%202016-04-19%20at%202.44.05%20PM.png?v=3026a0ac)

As you can see, the _cost_price_ and custom _UPC_ came over, but I do not see any _price_ property in the returned Bigcommerce Sku Object

**Comment by bonogit** [comment]
Same response I received using the gem. Here is my return value for sku:

<Bigcommerce::Sku bin_picking_number="" cost_price="0.0000" id=127 inventory_level=10 inventory_warning_level=0 options=[{:product_option_id=>114, :option_value_id=>98}] product_id=111 sku="var1" upc="">
