### ISSUE TITLE
Incorrect header check (Zlib::DataError)

### ISSUE THREAD

**Issue by stefansedich** [bigcommerce/bigcommerce-api-ruby#127]
I am getting this error attempting to use the API, I did another test locally and attempted to make the request by using Net::HTTP and turning off accept-encoding, and then I get a usefulish error back from the API:

200 HTML response with "This store is currently unavailable due to maintenance. It should be available again shortly.", I then attempted to use accept-encoding=gzip and handle the response myself but it did not appear to be a valid gzip stream.

I assume this error is because the store is under maintenance, but there seems to be an issue with the response from the API and the client unable to handle the gzipped contents or the response is invalid (and by default Ruby will pass through an accept-encoding header and handle decoding the response under the hood which explains the error).

One other interesting thing I did find was that on the "v3" version of the API I get a more useful error as JSON "You are authorized but your scope does not include this resource." but I was not even sure that v3 was an available API as all documentation appears to reference v2.

**Comment by pedelman** [comment]
Thanks for reporting -- I will take a look!
