### ISSUE TITLE
Error connecting to API

### ISSUE THREAD

**Issue by rjfrizz** [bigcommerce/bigcommerce-api-ruby#131]
I'm new to Ruby and to the BC API so there may be something obvious that I'm missing. When I'm running the following code with the proper details replaced with my store's legacy API credentials:

```
require 'bigcommerce'

Bigcommerce.configure do |config|
  config.auth = 'legacy'
  # You will get this url when registering for an API key
  config.url = ENV['BC_API_ENDPOINT_LEGACY']
  config.username = ENV['BC_USERNAME']
  config.api_key = ENV['BC_API_KEY']
end

puts Bigcommerce::System.time
```

I get the following error: 

```
.../lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80) (Faraday::ConnectionFailed)
```

I appreciate any pointers.

**Comment by gregory** [comment]
So just by looking at the error you shared, this: ` Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)` sounds like it's missing a url somewhere. 

Can you try to put `puts ENV['BC_API_ENDPOINT_LEGACY']` right before the last line of your sample and see if this prints the points to your legacy endpoint?

**Comment by bonogit** [comment]
I think @gregory is right about the endpoint. It seems your call havn't get too far on the auth connection yet. You might try using tools like postman to verify your credential first, then try it on the gem.
