### ISSUE TITLE
V3 response

### ISSUE THREAD

**Issue by rajnik-co2** [bigcommerce/bigcommerce-api-ruby#134]
**url_prefix**
`https://api.bigcommerce.com/stores/{store_hash}/v3`

**Connection**
` connection = Bigcommerce::Connection.build(Bigcommerce::Config.new(client_id: 'test',store_hash: 'test', access_token: 'test'))
`
**API call**
`Bigcommerce::System.time(connection: connection)
`

**Error**
`Bigcommerce::Forbidden: {"error":"You are authorized but your scope does not include this resource."}`

**Comment by bookernath** [comment]
Hi @rajnik-co2, the time resource is not yet implemented in V3. Available endpoints as of this writing are documented in our swagger documentation here: https://github.com/bigcommerce/api/blob/master/swagger/v3-catalog.yaml

You can still hit V2 API endpoints with the same credentials, however.
