### ISSUE TITLE
support for the v3 API?

### ISSUE THREAD

**Issue by achadee** [bigcommerce/bigcommerce-api-ruby#140]
hey guys,

When are you guys going to release support for the most recent API. The gem has v2 hardcoded
https://github.com/bigcommerce/bigcommerce-api-ruby/blob/v1.0.0/lib/bigcommerce/config.rb#L11

Thanks

**Comment by pedelman** [comment]
Based on feedback I think we are trying to move towards auto code generation for the v3 api. I saw some discussion on https://github.com/bigcommerce/bigcommerce-api-ruby/pull/135#issuecomment-268344945 so I will close out for now.

I'll try and have a discussion internally about adding v3 support. It would be trivial to add v3 support to this Gem.

I will close this out for now, but appreciate the feedback!

**Comment by jduarte** [comment]
Hey @pedelman !

Did you guys had any update regarding the v3 support?

**Comment by eni9889** [comment]
Any updates on this?
