### ISSUE TITLE
Any chance of updating or removing/loosening the faraday version dependency?

### ISSUE THREAD

**Issue by gregblass** [bigcommerce/bigcommerce-api-ruby#172]
Hey there! I was addressing a dependabot alert on a project for another gem, which depends on faraday > 1.0. I'm running into a conflict because this gem is locked at '~> 0.11'. It looks like the current version of faraday is all the way up to 2.3.0.

Is there any chance of somehow removing or loosening up that dependency, or updating it to something more recent? It looks like that era of the gem was ~5-6 years ago.

If anyone has any insight as to why the dependency is locked there, that would at least be helpful to know. I was thinking of trying to remove that dependency from the gem locally - but I imagine it was added for a reason (maybe breaking changes in the gem)? Or, if someone has any knowledge of what would be required to update this gem to work with a later version of faraday - I wouldn't mind attempting a pull request.

Thank you in advance if anyone can help out here!

**Comment by gregblass** [comment]
🦗

**Comment by johnAirRobe** [comment]
BUMP

**Comment by gregblass** [comment]
@splittingred Hey there!

I posted this ~2.5 months ago and got no responses. No worries if your engineering team doesn't have the resources to maintain this anymore - but if that is the case - should it be sunsetted / discontinued / looking for maintainers, etc?

The Faraday dependency for this gem is super, super old and is causing issues (and depreciation warnings) in our production software, so I was wondering what the deal is here before we move away from it and write our own code.

Thank you!

**Comment by gregblass** [comment]
For anyone that's experiencing these depreciation warnings, I forked the multipart-post gem here:

https://github.com/gregblass/multipart-post.git

Then I set faraday to the latest 0.X.X release (gem 'faraday', '~> 0.17.5'), and the depreciation warnings are gone.

**Comment by bc-chaz** [comment]
@gregblass this should be addressed wtih https://github.com/bigcommerce/bigcommerce-api-ruby/pull/173

**Comment by gregblass** [comment]
Thank you so much @bc-johnhebron / @bc-chaz - and anyone else who helped make this happen!
