### ISSUE TITLE
Get all rules, skus etc for a single product does not seem to be supported

### ISSUE THREAD

**Issue by alexnesbitt** [bigcommerce/bigcommerce-api-ruby#58]
get_products_rules(options={}) returns all rules for all products.  Is this intentional, as I don't see it documented in API docs?

Shouldn't there be a get_product_rules(product_id) method (and similar for sku and other product related data)

If you think those should be included I will send pull request.  Please let me know.
Alex

**Comment by pedelman** [comment]
This has been added on the new 1.0.0.beta release. Please give it a try!
