### ISSUE TITLE
Missing create, update and delete product custom fields

### ISSUE THREAD

**Issue by thuringian** [bigcommerce/bigcommerce-api-ruby#83]
I've been reading the bigcommerce docs and the api allows to you create, update and delete a product's custom fields. However as far as I can tell the wrapper only provides the GET functions.

 https://developer.bigcommerce.com/api/stores/v2/products/custom_fields

**Comment by pedelman** [comment]
Hello! We have just rewrote the entire bigcommerce gem which now has support for everything! If you could give it a try that would be great. I will be actively maintaining this project so please feel free to reopen issues once you give the new version a try.
