### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by madhurranjan** [bigcommerce/bigcommerce-api-ruby#85]
Hi,

I've a couple of questions: 

1. :access_token  => 'ACCESS_TOKEN' . Is this client secret ? If not , how do I get this token ? 

2. I'm constantly getting a 401 unauthorized. I'm guessing bigcommerce has not yet authorized my app. Is there a way to start testing api (for example , fetch products) without waiting for the app to be authorized ? 

Thanks!

**Comment by pedelman** [comment]
Hello, please refer to the updated docs for and if you have any further questions, please reopen this issue. We have just released a brand new version which I hope will be much easier to maintain and use.
