### ISSUE TITLE
General Guidelines for new Developers

### ISSUE THREAD

**Issue by sandovalg** [bigcommerce/bigcommerce-api-ruby#99]
Might I suggest a simple walk-through guiding the beginner developers. There are questions like this one http://stackoverflow.com/questions/28100315/how-to-retrieve-data-from-bigcommerce-using-rails-application where it seems help is not readily available. 
A sample application that deals with one specific area of the API might be a blessing to new developers. An example in mind would be the ability to CRUD a product from a new demonstration store. 
Initial setup for Private and Public Applications, etc.

**Comment by pedelman** [comment]
Great idea! We have a hello-world library written in sinatra over here: https://github.com/bigcommerce/hello-world-app-ruby-sinatra

That should be a good guide to get started, we also have an open pull request to integrate the new version of the API client. Also take a look at our developer portal for more high level information: https://developer.bigcommerce.com/. 

I would love to have a very simple process to get developers writing applications, so if you run into any problems, feel free to ping me here.

**Comment by gregory** [comment]
Should we close this now @sandovalg @pedelman ?

**Comment by sandovalg** [comment]
Good question. I think this is best to begin collaboration on immediately. How can I help? The problem with the ruby-sinatra app is adding in another element. Correction, replacing a framework with a specific DSL.

If help is required let me know. Much appreciated. To answer @gregory question, shall we close this thread?
